textlist  <- list(intro1 = "Welcome to the MOOC (Massive Online Open Course) App for the Centre for Social Sciences. The aim of this web app is to help visualise European attitudes towards a number of issues, using data from the ninth wave of the European Social Survey (ESS9). The three main categories are Trust, Immigration and Satisfaction. After answering some survey questions you will be able to compare your own answers to answers given by general respondents.",
                  intro2 = "Click on the button below to start the survey.",
                  radar_intro = "A radar chart is a graphical method of displaying multivariate data in the form of a two-dimensional chart of three or more quantitative variables represented on axes starting from the same point. In our case, all twenty examined variables scale upwards from zero. (In the original ESS survey the three questions regarding immigration were scaled from 1 to 4. For consistency, these have been flipped and shifted so that the variables scale from 0 to 3.) For our radar charts, the higher a response is, the further away the point in the plot will be from the origin. Thus, if one gave the maximal response to each question, their results would show as a circle in the radar plots.",
                  radar_overview1 = "In this section you can see all variables included on a single radar plot. You can cycle throught the tabs above to see separate radar charts for the three categories.",
                  radar_overview2 = "On the radar plot to the left you can see the weighted median values displayed for all variables measured. A high value in a variable means the participants agreed to a greater extent, so a high trust score means the respondents are more trusting, and a high immigration score shows greater tolerance of immigrants.",
                  radar_overview3 = "Note: Most variables are scaled 0 to 10, with a few exceptions. Political fairness is scaled from 0 to 4, and three variables regarding immigration are scaled from 0 to 3.",
                  radar_trust1 = "In this section you can see a radar chart of the six variables that fall into the \"trust\" category. Three of these relate to personal trust, while the other three to trust towards institutions.",
                  radar_immigration1 = "In this section you can see a radar chart of the six variables that fall into the \"immigration\" category. Three of these relate to the perception towards the effect immigration has on one's country, while the other three to willingness towards letting immigrants into one's own country.",
                  radar_satisfaction1 = "In this section you can see a radar chart of the seven variables that fall into the \"satisfaction\" category. Four of these relate to personal satisfaction, while the other three to satisfaction with institutions."
                  )
